/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testMerge() {
        App classUnderTest = new App();
      int[] arr = {8, 4, 23, 42, 16, 15};
//      classUnderTest.mergeSort(arr);
      assertArrayEquals(arr, classUnderTest.mergeSort(arr));
    }
  @Test public void testMergeSize() {
    App classUnderTest = new App();
    int[] arr = {8, 4, 23, 42, 16, 15};
//      classUnderTest.mergeSort(arr);
    assertEquals(arr.length, classUnderTest.mergeSort(arr).length);
  }
  @Test public void testMergeLengthOf0() {
    App classUnderTest = new App();
    int[] arr = {8};
//      classUnderTest.mergeSort(arr);
    assertArrayEquals(arr, classUnderTest.mergeSort(arr));
  }
}
