/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }

  @Test
  public void testSEnqueueMethod() {
    Library classUnderTest = new Library();
    AnimalShelter animalShelter = new AnimalShelter();
    assertEquals("Shelter{front=null, rear=null}", animalShelter.toString());
    animalShelter.enqueue("cat");
    assertEquals("Shelter{front=Node{animal=cat, next=null}, rear=Node{animal=cat, next=null}}", animalShelter.toString());
    animalShelter.enqueue("dog");
    assertEquals("Shelter{front=Node{animal=cat, next=Node{animal=dog, next=null}}, rear=Node{animal=dog, next=null}}", animalShelter.toString());
  }

  @Test
  public void testSDequeueMethod() {
    Library classUnderTest = new Library();
    AnimalShelter animalShelter = new AnimalShelter();
    animalShelter.enqueue("cat");
    animalShelter.enqueue("dog");
    System.out.println(animalShelter.dequeue("cat"));
    assertEquals("Shelter{front=Node{animal=dog, next=null}, rear=Node{animal=dog, next=null}}", animalShelter.toString());
    System.out.println(animalShelter.dequeue("dog"));
    assertEquals("Shelter{front=null, rear=Node{animal=dog, next=null}}", animalShelter.toString());
    System.out.println(animalShelter.dequeue("turtles"));
    assertEquals("Shelter{front=null, rear=Node{animal=dog, next=null}}", animalShelter.toString());
  }
}
