/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ArrayShift;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;

public class ArrayShiftTest {
    @Test public void testSomeLibraryMethod() {
        ArrayShift classUnderTest = new ArrayShift();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

  @Test
public void testInsertShiftArray(){

    ArrayShift classUnderTest = new ArrayShift();
    ArrayList<Integer>expectedArray=new ArrayList<>();

    int[] array={4,8,15,23,42};
    int[] outArray={4,8,15,16,23,42};

    for(int i=0;i<outArray.length;i++){
      expectedArray.add(outArray[i]);
    }

    ArrayList<Integer> arrayTest=classUnderTest.insertShiftArray(array,16);

//    System.out.println("expectedArray is : "+expectedArray);
    System.out.println("arrayTest is : "+arrayTest);
    assertEquals(expectedArray.size(),arrayTest.size());
//    assertTrue(true);

    }
}
