/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import GetEdge.GetEdge;

import java.util.ArrayList;

public class Library {
  public boolean someLibraryMethod() {
    return true;

  }

  public static void main(String[] args) {
//    int[] arr = {0, 1, 2, 0, 1, 2};
//    int[] arr = {0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1};
//    sortArr(arr);
//    for (int i = 0; i < arr.length; i++) {
//      System.out.print(arr[i] + ",");
//    }

  }

  public static void sortArr(int[] arr) {
    //second
    int tows = 1,zeros = 0;
    for (int i = 0; i < arr.length; i++) {
      if (arr[i] == 0) {
        arr[i] = arr[zeros];
        arr[zeros] = 0;
        zeros++;
      }
      if (arr[i] == 2&&arr.length-tows>i) {
        arr[i] = arr[arr.length - tows];
        arr[arr.length - tows] = 2;
        i--;
        tows++;
      }
    }
    //third solution
//    int ones = 0, zeros = 0;
//    for (int i = 0; i < arr.length; i++) {
//      if (arr[i] == 0) {
//        zeros++;
//      } else if (arr[i] == 1) {
//        ones++;
//      }
//    }
//      for (int j = 0; j < zeros; j++) {
//        arr[j] = 0;
//      }
//      for (int j = zeros; j < zeros + ones; j++) {
//        arr[j] = 1;
//      }
//      for (int j = zeros + ones; j < arr.length; j++) {
//        arr[j] = 2;
//      }


  }
}
