/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

public class Library {

  public static void main(String[] args) {
      //STACK
    Stack stack=new Stack();
    System.out.println(stack.isEmpty());
    System.out.println(stack.peek());
    stack.push(4);
    stack.push(6);
    stack.push(8);
    System.out.println(stack);
    System.out.println(stack.peek());
    System.out.println(stack.pop());
    System.out.println(stack);
    System.out.println(stack.peek());
    System.out.println(stack.pop());
    System.out.println(stack);

////    System.out.println(stack.pop());
//    System.out.println(stack.peek());
//    System.out.println(stack.isEmpty());
//    System.out.println(stack);

//Queue
    Queue queue=new Queue();
    queue.enqueue(3);
    queue.enqueue(5);
    queue.enqueue(7);
queue.enqueue(9);
    System.out.println(queue);
    System.out.println(queue.dequeue());
    System.out.println(queue.peek());
    System.out.println(queue);
    System.out.println(queue.dequeue());
    System.out.println(queue.peek());
    System.out.println(queue);

  }

}
