/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppQuickSortFullArray() {
        App classUnderTest = new App();
      int[] array={8,4,23,42,16,15};
      int[] sortedArray = {4, 8, 15, 16, 23, 42};
assertEquals(sortedArray.length,classUnderTest.QuickSort(array,0,array.length-1).length);
      assertArrayEquals(sortedArray,classUnderTest.QuickSort(array,0,array.length-1));
    }
  @Test public void testAppQuickSortSubArray() {
    App classUnderTest = new App();
    int[] arr={8,4,23,42,16,15};
    int[] sortedArray = {4, 8, 23, 42,16, 15};

    assertArrayEquals(sortedArray,classUnderTest.QuickSort(arr,0,arr.length-3));
  }
  @Test public void testAppQuickSortMidArray() {
    App classUnderTest = new App();
    int[] arr={8,4,23,42,16,15};
    int[] sortedArray = {8,4,16,23,42,15};

    assertArrayEquals(sortedArray,classUnderTest.QuickSort(arr,2,arr.length-2));
  }
  @Test public void testAppArrayOfOne() {
    App classUnderTest = new App();
    int[] arr={8};
    int[] sortedArray = {8};

    assertArrayEquals(sortedArray,classUnderTest.QuickSort(arr,2,arr.length-2));
  }
}
