/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.Test;

import static linkedList.LinkedList.zipLists;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testInclodesMethod() {
        LinkedList classUnderTest = new LinkedList();
        classUnderTest.insert(7);
        assertEquals("the value that insert is inclode ", true,classUnderTest.includes(7));
      assertEquals("the value that insert is inclode ", false,classUnderTest.includes(8));


    }
  @Test public void testToStringMethod() {
    LinkedList classUnderTest = new LinkedList();
    classUnderTest.insert(7);
    classUnderTest.insert(8);
    classUnderTest.toString();
    String testString="{8}->{7}->Null";
//    assertEquals("the value that insert is inclode ", true,classUnderTest.includes(7));
    assertEquals("",testString,classUnderTest.toString());


  }
  @Test
  public void testFindNodeK(){
    LinkedList linkedList = new LinkedList();
    linkedList.insert(7);

    linkedList.insert(8);

    linkedList.append(5);
    linkedList.append(6);
    linkedList.insertBefore(6, 9);
    linkedList.insertAfter(5, 2);

//    System.out.println(linkedList.toString());
//linkedList.findK(2);
    System.out.println("Node of K :"+linkedList.findNodeK(1));
//    assertTrue(true);
    assertEquals(9,linkedList.findNodeK(1));
  }

@Test
  public void testZipLists(){
  LinkedList linkedList1=new LinkedList();
  linkedList1.insert(1);
  linkedList1.append(2);
  linkedList1.append(3);
  LinkedList linkedList2=new LinkedList();
  linkedList2.insert(20);
  linkedList2.append(30);
  linkedList2.append(40);
  System.out.println("linked List 1 : "+linkedList1.toString());

  System.out.println("linked List 2 : "+linkedList2.toString());
  zipLists(linkedList1,linkedList2);
  System.out.println("Zip linked List : "+linkedList1.toString());
  assertEquals("{1}->{20}->{2}->{30}->{3}->{40}->Null",linkedList1.toString());
}

}
