/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BinarySearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
  @Test public void BinarySearchTest(){

       int[] a={4,8,15,16,23,42};
//    int[] b={11,22,33,44,55,66,77};
//    int[] c={1, 2, 3, 5, 6, 7};
    //   int[] d={4,8,14,15,16,23,42};
    //   int[] f={4,8,9,10,15,16,17,23,42};
    //  int[] g={4,5,6,7,8,9,10,15,16,17};
    int keyA=15;
//    int keyB=90;
//    int keyC=4;

    Library BinarySearchUnderTest = new Library();
    int index=BinarySearchUnderTest.BinarySearch(a,keyA);

//assertEquals(2,index);
assertEquals("The index of key",2,index);
//
////        assertEquals("The first item is equal to 5","5",reversed.get(3));
//
//      assertEquals("Both sizes are the same", rollArray.size(),4);
//    }

  }
}
