/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {

    public static void main(String[] args) {
Hashtable hashtable=new Hashtable();
      System.out.println(hashtable.get("groot"));

      hashtable.add("groot", "esraa");

      System.out.println(new Hashtable().hash("groot"));
      System.out.println(hashtable);
      System.out.println(hashtable.get("groot"));
      System.out.println(hashtable.get("esraa"));
      System.out.println(hashtable.contains("groot"));
      System.out.println(hashtable.contains("esraa"));

    }
}
