/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BinarySearch;

public class Library {
  public static int BinarySearch (int[]arr,int key) {
    int indexOfKey=-1;
    int newLength = 0, originalLength = arr.length - 1;
    while (newLength <= originalLength) {
      int mid = newLength+ (originalLength - newLength) / 2;

      // Check if x is present at mid
      if (arr[mid] == key)
        return mid;

      // If x greater, ignore left half
      if (arr[mid] < key)
        newLength = mid + 1;

        // If x is smaller, ignore right half
      else
        originalLength = mid - 1;
    }
    return indexOfKey;
  }
}
    //   int mid=0;
//     int higherBondary=0;
//   int lowerBondary=0;

// int midIndex=0;
// for(int i=0;i<arr.length;i++){
//   mid=arr[arr.length/2];
//     System.out.println(mid);
//  if(arr.length%2==0){
//  midIndex=arr.length/2;
// }else{
//  midIndex=(arr.length/2)+1;
// }
//   if (key==mid){
// indexOfKey=midIndex;
//     System.out.println(indexOfKey);
//     break;
//   }
//   else if(key<mid){
// for(int j=0;j<midIndex;j++){
//     if (key==mid){
// indexOfKey=midIndex;
//     System.out.println(indexOfKey);
//     break;
//   }
// }
//   }
//   else {
//   }

