/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QuickSort;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppQuickSortFullArray() {
        App classUnderTest = new App();
      int[] array={8,4,23,42,16,15};
      int[] sortedArray = {4, 8, 15, 16, 23, 42};
assertEquals(sortedArray.length,classUnderTest.QuickSort(array,0,array.length-1).length);
      assertArrayEquals(sortedArray,classUnderTest.QuickSort(array,0,array.length-1));
    }
  @Test public void testAppQuickSorEmptyArray() {
    App classUnderTest = new App();
    int[] array={};
    assertEquals(array.length,classUnderTest.QuickSort(array,0,array.length-1).length);
    assertArrayEquals( array,classUnderTest.QuickSort(array,0,array.length-1));
  }
  @Test public void testAppArrayOfOne() {
    App classUnderTest = new App();
    int[] arr={8};
    int[] sortedArray = {8};

    assertArrayEquals(sortedArray,classUnderTest.QuickSort(arr,2,arr.length-2));
  }
//  Reverse-sorted: [20,18,12,8,5,-2]

@Test public void testAppQuickSortReverseSortedArray() {
  App classUnderTest = new App();
  int[] array={20,18,12,8,5,-2};
  int[] sortedArray = {-2,5,8,12,18,20};
  assertEquals(sortedArray.length,classUnderTest.QuickSort(array,0,array.length-1).length);
  assertArrayEquals(sortedArray,classUnderTest.QuickSort(array,0,array.length-1));
}
  @Test public void testAppQuickSortFewUniquesArray() {
    //  Few uniques: [5,12,7,5,5,7]
    App classUnderTest = new App();
    int[] array={5,12,7,5,5,7};
    int[] sortedArray = {5,5,5,7,7,12};
    assertEquals(sortedArray.length,classUnderTest.QuickSort(array,0,array.length-1).length);
    assertArrayEquals(sortedArray,classUnderTest.QuickSort(array,0,array.length-1));
  }
  @Test public void testAppQuickSortNearlySortedArray() {
//  Nearly-sorted: [2,3,5,7,13,11]
    App classUnderTest = new App();
    int[] array={2,3,5,7,13,11};
    int[] sortedArray = {2,3,5,7,11,13};
    assertEquals(sortedArray.length,classUnderTest.QuickSort(array,0,array.length-1).length);
    assertArrayEquals(sortedArray,classUnderTest.QuickSort(array,0,array.length-1));
  }

}
