/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
   
  @Test
  public void testInsertionSort() {
    Library classUnderTest2 = new Library();

    int[] array = {8, 4, 23, 42, 16, 15};
    int[] sortedArray = {4, 8, 15, 16, 23, 42};
    classUnderTest2.InsertionSort(array);
    assertArrayEquals(sortedArray,classUnderTest2.InsertionSort(array));
//    for (int i = 0; i < array.length; i++) {
//      System.out.println(array[i]+"<>"+sortedArray[i]);
//      assertEquals(array[i], sortedArray[i]);
//    }

//    assertTrue(true);
  }
  @Test
  public void testInsertionSize(){
    Library classUnderTest2 = new Library();

    int[] array = {8, 4, 23, 42, 16, 15};
    assertEquals(array.length,classUnderTest2.InsertionSort(array).length);
  }
  @Test
  public void testInsertionWithSizeOfOne(){
    Library classUnderTest2 = new Library();

    int[] array = {8};
    assertArrayEquals(array,classUnderTest2.InsertionSort(array));
//    assertEquals(,classUnderTest2.InsertionSort(array));
  }

}
