/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utilities;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

  public static void main(String[] args) {
    //Queue
    AnimalShelter animalShelter=new AnimalShelter();
    animalShelter.enqueue("cat");
    animalShelter.enqueue("dog");

    System.out.println(animalShelter);
    System.out.println(animalShelter.dequeue("cat"));
    System.out.println(animalShelter.dequeue("dog"));
    System.out.println(animalShelter.dequeue("turtles"));


//    System.out.println(queue.peek());
//    System.out.println(queue);
//    System.out.println(queue.dequeue());
//    System.out.println(queue.peek());
//    System.out.println(queue);

  }
}
